### ISSUE TITLE
Support Message sent to client uses staff notify

### ISSUE THREAD

**Issue by Stoopler** [StackOverNorth/ButlerSpeak#3]
A user joining the designated support channel is sent the "support.notify-message" instead of "support.message".

No idea why, but I can't seem to get this to work properly.

**Comment by StackOverNorth** [comment]
https://github.com/StackOverNorth/ButlerSpeak/blob/4334c320f28acf7fa85dd0a2a3f908888261aeef/src/main/java/me/floody/butlerspeak/plugins/SupportManager.java#L90-L95
Excuse the late reply! As you can see, everyone who's in the notification group, defined by your configuration file, will receive `support.notify-message` and the client who triggered the events, receives the `support.message` message.

Please ensure that your configuration file looks (kinda) like this:
https://github.com/StackOverNorth/ButlerSpeak/blob/4334c320f28acf7fa85dd0a2a3f908888261aeef/src/main/resources/ButlerSpeak_EXAMPLE.properties#L155-L160
Btw, I tested this feature, and it worked fine for me. If you need further assistance, please hit me up.

**Comment by StackOverNorth** [comment]
So, I re-looked at your issue. I cannot find any issues with the code and the bots works as intended on my end. Eventually, the issue must be in your configuration file.

If you're running into any other issues, please open a new ticket or if it's the same issue, please re-open by yourself.
